create table car (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	make VARCHAR(100) NOT NULL,
	model VARCHAR(100) NOT NULL,
	price VARCHAR(50) NOT NULL
);
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '$5146.52');
insert into car (make, model, price) values ('Buick', 'Rendezvous', '$1387.59');
insert into car (make, model, price) values ('Ford', 'F250', '$8684.60');
insert into car (make, model, price) values ('Nissan', 'Sentra', '$8097.37');
insert into car (make, model, price) values ('Porsche', '924 S', '$5149.09');
insert into car (make, model, price) values ('Mazda', 'RX-8', '$7446.68');
insert into car (make, model, price) values ('Ford', 'Mustang', '$4673.55');
insert into car (make, model, price) values ('Dodge', 'Viper', '$5005.50');
insert into car (make, model, price) values ('Volvo', 'S60', '$1770.07');
insert into car (make, model, price) values ('Mazda', 'RX-8', '$4355.87');
insert into car (make, model, price) values ('Acura', 'Legend', '$6465.31');
insert into car (make, model, price) values ('Suzuki', 'Grand Vitara', '$5267.45');
insert into car (make, model, price) values ('GMC', 'Yukon Denali', '$7408.94');
insert into car (make, model, price) values ('Toyota', 'Tacoma', '$7282.54');
insert into car (make, model, price) values ('Pontiac', 'Grand Am', '$3075.81');
insert into car (make, model, price) values ('Volvo', 'S70', '$3769.76');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '$5338.64');
insert into car (make, model, price) values ('Porsche', '944', '$2230.42');
insert into car (make, model, price) values ('Mazda', 'MPV', '$1365.73');
insert into car (make, model, price) values ('Bentley', 'Continental GT', '$7365.10');
insert into car (make, model, price) values ('Toyota', '4Runner', '$7812.50');
insert into car (make, model, price) values ('Dodge', 'Ram Wagon B250', '$6996.85');
insert into car (make, model, price) values ('Nissan', 'Quest', '$5050.42');
insert into car (make, model, price) values ('Toyota', 'MR2', '$6974.17');
insert into car (make, model, price) values ('BMW', '530', '$8125.27');
insert into car (make, model, price) values ('Pontiac', 'Fiero', '$7741.57');
insert into car (make, model, price) values ('Saturn', 'S-Series', '$2656.20');
insert into car (make, model, price) values ('Toyota', 'Prius', '$4481.12');
insert into car (make, model, price) values ('Toyota', 'Supra', '$8017.29');
insert into car (make, model, price) values ('Porsche', 'Cayman', '$6733.98');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '$6892.58');
insert into car (make, model, price) values ('Volkswagen', 'Jetta III', '$2376.82');
insert into car (make, model, price) values ('Aston Martin', 'DBS', '$2183.71');
insert into car (make, model, price) values ('GMC', 'Savana', '$2576.29');
insert into car (make, model, price) values ('Chevrolet', 'Cobalt SS', '$1779.61');
insert into car (make, model, price) values ('Dodge', 'Journey', '$1954.74');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '$8973.15');
insert into car (make, model, price) values ('Chevrolet', 'Express 3500', '$5423.58');
insert into car (make, model, price) values ('Honda', 'CR-V', '$8451.58');
insert into car (make, model, price) values ('Chevrolet', 'Camaro', '$8357.34');
insert into car (make, model, price) values ('Mitsubishi', '3000GT', '$4004.08');
insert into car (make, model, price) values ('Chevrolet', 'S10', '$8094.09');
insert into car (make, model, price) values ('Chevrolet', 'Astro', '$8460.49');
insert into car (make, model, price) values ('Cadillac', 'Eldorado', '$6271.13');
insert into car (make, model, price) values ('Pontiac', 'Montana', '$8337.83');
insert into car (make, model, price) values ('Kia', 'Sephia', '$7291.11');
insert into car (make, model, price) values ('GMC', 'Sierra 2500', '$7155.15');
insert into car (make, model, price) values ('Audi', 'A4', '$3800.86');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '$5562.56');
insert into car (make, model, price) values ('Mitsubishi', 'Mighty Max', '$7110.96');
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', '$5431.47');
insert into car (make, model, price) values ('Chevrolet', 'Silverado', '$3830.62');
insert into car (make, model, price) values ('GMC', 'Sierra 1500', '$2532.06');
insert into car (make, model, price) values ('GMC', 'Rally Wagon 3500', '$8932.47');
insert into car (make, model, price) values ('Kia', 'Rio', '$3549.99');
insert into car (make, model, price) values ('Dodge', 'Avenger', '$6932.81');
insert into car (make, model, price) values ('Honda', 'Odyssey', '$9368.80');
insert into car (make, model, price) values ('Hyundai', 'Sonata', '$8477.41');
insert into car (make, model, price) values ('Ford', 'Econoline E350', '$7433.01');
insert into car (make, model, price) values ('Chevrolet', 'S10', '$4132.36');
insert into car (make, model, price) values ('Volkswagen', 'rio', '$5130.57');
insert into car (make, model, price) values ('Land Rover', 'Discovery', '$3320.72');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '$1389.93');
insert into car (make, model, price) values ('Isuzu', 'Trooper', '$1063.21');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '$8218.51');
insert into car (make, model, price) values ('Chevrolet', 'Astro', '$1465.57');
insert into car (make, model, price) values ('Ford', 'Thunderbird', '$3226.27');
insert into car (make, model, price) values ('Mitsubishi', 'Galant', '$1821.54');
insert into car (make, model, price) values ('Ford', 'E150', '$9037.22');
insert into car (make, model, price) values ('Chevrolet', 'Lumina', '$3188.88');
insert into car (make, model, price) values ('Mercury', 'Villager', '$1780.01');
insert into car (make, model, price) values ('Dodge', 'Colt', '$4447.82');
insert into car (make, model, price) values ('Dodge', 'Ram 3500', '$5958.03');
insert into car (make, model, price) values ('Isuzu', 'Rodeo', '$8841.07');
insert into car (make, model, price) values ('Cadillac', 'CTS', '$6275.99');
insert into car (make, model, price) values ('Audi', 'Q7', '$9670.46');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '$4166.54');
insert into car (make, model, price) values ('Mazda', 'RX-7', '$3255.97');
insert into car (make, model, price) values ('Cadillac', 'DeVille', '$3400.69');
insert into car (make, model, price) values ('Jeep', 'Wrangler', '$7624.23');
insert into car (make, model, price) values ('Acura', 'RL', '$1795.43');
insert into car (make, model, price) values ('Pontiac', 'Sunfire', '$1756.18');
insert into car (make, model, price) values ('Toyota', 'Tercel', '$4710.21');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 2500', '$6019.20');
insert into car (make, model, price) values ('Mitsubishi', 'Truck', '$1719.80');
insert into car (make, model, price) values ('Mercury', 'Tracer', '$1194.78');
insert into car (make, model, price) values ('Toyota', 'Tundra', '$1488.05');
insert into car (make, model, price) values ('Mercedes-Benz', '300SD', '$3703.78');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '$8705.17');
insert into car (make, model, price) values ('Maserati', '228', '$2308.86');
insert into car (make, model, price) values ('Lexus', 'LS', '$9138.85');
insert into car (make, model, price) values ('Lexus', 'ES', '$1340.49');
insert into car (make, model, price) values ('Ferrari', '458 Italia', '$2551.38');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '$9001.99');
insert into car (make, model, price) values ('Dodge', 'Daytona', '$4413.62');
insert into car (make, model, price) values ('Ford', 'Fusion', '$3695.73');
insert into car (make, model, price) values ('Ford', 'Expedition', '$6055.47');
insert into car (make, model, price) values ('Pontiac', 'Bonneville', '$9039.79');
insert into car (make, model, price) values ('Kia', 'Sephia', '$6587.73');
insert into car (make, model, price) values ('Nissan', 'Rogue', '$7272.53');
insert into car (make, model, price) values ('Mercury', 'Sable', '$4317.38');
insert into car (make, model, price) values ('GMC', 'Sonoma Club Coupe', '$9065.28');
insert into car (make, model, price) values ('Mercury', 'Monterey', '$4094.55');
insert into car (make, model, price) values ('Saab', '9-5', '$4224.38');
insert into car (make, model, price) values ('Mazda', 'B2500', '$8395.66');
insert into car (make, model, price) values ('Chrysler', 'Sebring', '$9622.11');
insert into car (make, model, price) values ('Acura', 'NSX', '$7624.80');
insert into car (make, model, price) values ('Nissan', 'Sentra', '$5799.88');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '$1967.93');
insert into car (make, model, price) values ('Alfa Romeo', '164', '$5073.58');
insert into car (make, model, price) values ('GMC', 'Savana 1500', '$8862.07');
insert into car (make, model, price) values ('Nissan', 'Murano', '$6454.46');
insert into car (make, model, price) values ('Mitsubishi', 'Galant', '$7499.02');
insert into car (make, model, price) values ('Toyota', 'RAV4', '$6236.52');
insert into car (make, model, price) values ('GMC', 'Yukon XL 1500', '$1575.72');
insert into car (make, model, price) values ('Isuzu', 'Stylus', '$9327.02');
insert into car (make, model, price) values ('Lincoln', 'Mark VIII', '$7230.99');
insert into car (make, model, price) values ('Mercedes-Benz', '600SEL', '$3873.05');
insert into car (make, model, price) values ('Chevrolet', 'Cobalt SS', '$6052.19');
insert into car (make, model, price) values ('Toyota', 'Avalon', '$3227.55');
insert into car (make, model, price) values ('Lexus', 'GX', '$9540.40');
insert into car (make, model, price) values ('Cadillac', 'Catera', '$3739.27');
insert into car (make, model, price) values ('Plymouth', 'Reliant', '$1053.91');
insert into car (make, model, price) values ('Ford', 'Fairlane', '$1091.17');
insert into car (make, model, price) values ('BMW', 'M3', '$5065.84');
insert into car (make, model, price) values ('Porsche', 'Carrera GT', '$9962.25');
insert into car (make, model, price) values ('Cadillac', 'Seville', '$4740.97');
insert into car (make, model, price) values ('Nissan', 'Armada', '$6986.73');
insert into car (make, model, price) values ('GMC', '1500 Club Coupe', '$3987.84');
insert into car (make, model, price) values ('Kia', 'Rio', '$8702.27');
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', '$3832.61');
insert into car (make, model, price) values ('Volvo', 'S40', '$5786.54');
insert into car (make, model, price) values ('Mercury', 'Mountaineer', '$3330.08');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '$3879.52');
insert into car (make, model, price) values ('Mercedes-Benz', 'CL-Class', '$5928.70');
insert into car (make, model, price) values ('Maybach', '57', '$5804.62');
insert into car (make, model, price) values ('Ford', 'E350', '$5019.06');
insert into car (make, model, price) values ('Lamborghini', 'Countach', '$3746.32');
insert into car (make, model, price) values ('Toyota', '4Runner', '$1433.35');
insert into car (make, model, price) values ('Mazda', 'CX-7', '$2975.39');
insert into car (make, model, price) values ('Pontiac', 'LeMans', '$8978.87');
insert into car (make, model, price) values ('Nissan', 'Frontier', '$6653.64');
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', '$5032.25');
insert into car (make, model, price) values ('Ford', 'Expedition', '$9305.94');
insert into car (make, model, price) values ('Chevrolet', 'Beretta', '$3769.94');
insert into car (make, model, price) values ('Ford', 'Thunderbird', '$1755.98');
insert into car (make, model, price) values ('Oldsmobile', 'Bravada', '$6125.77');
insert into car (make, model, price) values ('Honda', 'Fit', '$2417.98');
insert into car (make, model, price) values ('Toyota', 'Tacoma', '$9128.32');
insert into car (make, model, price) values ('Subaru', 'Forester', '$1223.31');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '$9703.01');
insert into car (make, model, price) values ('Ford', 'Taurus', '$2385.91');
insert into car (make, model, price) values ('Saab', '9000', '$5534.24');
insert into car (make, model, price) values ('Porsche', '944', '$7143.88');
insert into car (make, model, price) values ('Audi', '5000S', '$5093.87');
insert into car (make, model, price) values ('Mitsubishi', 'Pajero', '$9920.06');
insert into car (make, model, price) values ('Porsche', '911', '$9938.15');
insert into car (make, model, price) values ('Honda', 'Insight', '$1148.75');
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', '$4626.21');
insert into car (make, model, price) values ('Ford', 'Taurus', '$8045.48');
insert into car (make, model, price) values ('Lincoln', 'Continental', '$8649.16');
insert into car (make, model, price) values ('Pontiac', 'Grand Am', '$3665.77');
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', '$4322.17');
insert into car (make, model, price) values ('Volkswagen', 'Touareg 2', '$4410.00');
insert into car (make, model, price) values ('Porsche', '911', '$7300.84');
insert into car (make, model, price) values ('GMC', 'Savana 3500', '$3715.86');
insert into car (make, model, price) values ('Ford', 'Aerostar', '$6408.37');
insert into car (make, model, price) values ('Ford', 'F150', '$7224.60');
insert into car (make, model, price) values ('Honda', 'Prelude', '$1984.90');
insert into car (make, model, price) values ('Maybach', '62', '$8794.06');
insert into car (make, model, price) values ('Suzuki', 'SJ 410', '$1926.30');
insert into car (make, model, price) values ('Mercedes-Benz', 'M-Class', '$3114.24');
insert into car (make, model, price) values ('Mitsubishi', 'Challenger', '$6122.62');
insert into car (make, model, price) values ('Mercedes-Benz', 'CL-Class', '$3267.40');
insert into car (make, model, price) values ('Audi', 'A6', '$6060.28');
insert into car (make, model, price) values ('Mitsubishi', 'Galant', '$1516.65');
insert into car (make, model, price) values ('Kia', 'Sedona', '$7399.35');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', '$7251.30');
insert into car (make, model, price) values ('Toyota', 'Tacoma Xtra', '$9948.70');
insert into car (make, model, price) values ('Ford', 'F450', '$2800.30');
insert into car (make, model, price) values ('Chevrolet', 'Cobalt', '$5300.77');
insert into car (make, model, price) values ('GMC', 'Canyon', '$5250.58');
insert into car (make, model, price) values ('Eagle', 'Talon', '$9825.37');
insert into car (make, model, price) values ('Honda', 'Prelude', '$3482.83');
insert into car (make, model, price) values ('Saturn', 'VUE', '$5737.29');
insert into car (make, model, price) values ('Ford', 'Explorer', '$4644.59');
insert into car (make, model, price) values ('Ford', 'Ranger', '$4590.82');
insert into car (make, model, price) values ('Mazda', 'Mazda5', '$5774.67');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '$8934.82');
insert into car (make, model, price) values ('Ford', 'Econoline E350', '$4000.16');
insert into car (make, model, price) values ('Pontiac', 'Bonneville', '$1061.22');
insert into car (make, model, price) values ('Mercury', 'Mystique', '$6982.10');
insert into car (make, model, price) values ('Nissan', 'Xterra', '$4554.93');
insert into car (make, model, price) values ('Plymouth', 'Neon', '$4027.80');
insert into car (make, model, price) values ('Dodge', 'Dakota', '$4701.33');
insert into car (make, model, price) values ('Pontiac', 'Grand Am', '$1233.41');
insert into car (make, model, price) values ('BMW', 'X5', '$4698.20');
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', '$6503.72');
insert into car (make, model, price) values ('Chevrolet', 'Impala', '$6667.52');
insert into car (make, model, price) values ('Toyota', 'MR2', '$6358.26');
insert into car (make, model, price) values ('Chevrolet', 'Express 3500', '$9805.10');
insert into car (make, model, price) values ('Volvo', 'V50', '$5193.89');
insert into car (make, model, price) values ('Jeep', 'Wrangler', '$2379.97');
insert into car (make, model, price) values ('GMC', 'Yukon', '$1694.50');
insert into car (make, model, price) values ('Acura', 'TSX', '$4594.22');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '$6002.81');
insert into car (make, model, price) values ('Mazda', 'MPV', '$9168.55');
insert into car (make, model, price) values ('Ford', 'F150', '$4199.02');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '$5669.65');
insert into car (make, model, price) values ('Porsche', 'Boxster', '$8067.18');
insert into car (make, model, price) values ('Dodge', 'Dakota Club', '$5379.31');
insert into car (make, model, price) values ('Mercedes-Benz', 'CL-Class', '$8820.48');
insert into car (make, model, price) values ('Ford', 'E150', '$3680.43');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '$2777.27');
insert into car (make, model, price) values ('Dodge', 'Dakota', '$3412.72');
insert into car (make, model, price) values ('Buick', 'Coachbuilder', '$4638.33');
insert into car (make, model, price) values ('GMC', 'Savana 3500', '$9646.50');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 1500', '$3416.24');
insert into car (make, model, price) values ('BMW', '7 Series', '$5190.84');
insert into car (make, model, price) values ('Ford', 'F350', '$4909.99');
insert into car (make, model, price) values ('Hyundai', 'Tiburon', '$8046.94');
insert into car (make, model, price) values ('Toyota', 'Highlander Hybrid', '$5783.46');
insert into car (make, model, price) values ('Ford', 'Freestar', '$1648.61');
insert into car (make, model, price) values ('GMC', 'Vandura 1500', '$4344.52');
insert into car (make, model, price) values ('Honda', 'Passport', '$4027.11');
insert into car (make, model, price) values ('Honda', 'Civic', '$9655.87');
insert into car (make, model, price) values ('Isuzu', 'Rodeo', '$8523.74');
insert into car (make, model, price) values ('Dodge', 'Ramcharger', '$7818.72');
insert into car (make, model, price) values ('Mitsubishi', 'Truck', '$9613.40');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', '$2070.78');
insert into car (make, model, price) values ('Pontiac', 'Bonneville', '$9784.06');
insert into car (make, model, price) values ('Land Rover', 'Defender', '$4811.28');
insert into car (make, model, price) values ('Mercury', 'Cougar', '$9158.20');
insert into car (make, model, price) values ('Jeep', 'Commander', '$5349.47');
insert into car (make, model, price) values ('Oldsmobile', '98', '$3684.52');
insert into car (make, model, price) values ('Mercedes-Benz', 'M-Class', '$1491.41');
insert into car (make, model, price) values ('Nissan', 'Quest', '$4615.65');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '$2654.20');
insert into car (make, model, price) values ('Ford', 'Taurus', '$5864.65');
insert into car (make, model, price) values ('Infiniti', 'G', '$1028.36');
insert into car (make, model, price) values ('Volkswagen', 'Jetta III', '$2065.32');
insert into car (make, model, price) values ('Chrysler', 'Town & Country', '$3648.35');
insert into car (make, model, price) values ('Buick', 'Century', '$3293.97');
insert into car (make, model, price) values ('Jeep', 'Cherokee', '$3946.18');
insert into car (make, model, price) values ('Ford', 'Bronco', '$1237.88');
insert into car (make, model, price) values ('Jaguar', 'X-Type', '$9899.32');
insert into car (make, model, price) values ('Ford', 'Explorer', '$3072.47');
insert into car (make, model, price) values ('Buick', 'Rendezvous', '$6184.32');
insert into car (make, model, price) values ('Saturn', 'S-Series', '$6604.92');
insert into car (make, model, price) values ('Audi', 'Q7', '$5120.89');
insert into car (make, model, price) values ('Ford', 'Econoline E150', '$1758.38');
insert into car (make, model, price) values ('Infiniti', 'FX', '$4958.01');
insert into car (make, model, price) values ('Maserati', '430', '$3043.40');
insert into car (make, model, price) values ('Chrysler', '300', '$9660.56');
insert into car (make, model, price) values ('Volvo', 'S40', '$3299.17');
insert into car (make, model, price) values ('Ford', 'Mustang', '$5115.53');
insert into car (make, model, price) values ('Lotus', 'Esprit', '$9337.70');
insert into car (make, model, price) values ('Dodge', 'Ram Van 3500', '$1232.45');
insert into car (make, model, price) values ('Mercedes-Benz', 'M-Class', '$1039.80');
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', '$8865.24');
insert into car (make, model, price) values ('Oldsmobile', 'Alero', '$8078.52');
insert into car (make, model, price) values ('Dodge', 'Ram 2500', '$2898.63');
insert into car (make, model, price) values ('Acura', 'MDX', '$3427.87');
insert into car (make, model, price) values ('Infiniti', 'M', '$4485.25');
insert into car (make, model, price) values ('Kia', 'Sorento', '$7664.65');
insert into car (make, model, price) values ('Oldsmobile', 'Ciera', '$7354.27');
insert into car (make, model, price) values ('Toyota', 'Sienna', '$9657.55');
insert into car (make, model, price) values ('Plymouth', 'Grand Voyager', '$1112.09');
insert into car (make, model, price) values ('Ford', 'F-Series', '$2679.24');
insert into car (make, model, price) values ('Volkswagen', 'GTI', '$7623.44');
insert into car (make, model, price) values ('Jeep', 'Liberty', '$8044.33');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix Turbo', '$6667.54');
insert into car (make, model, price) values ('Porsche', 'Boxster', '$5549.10');
insert into car (make, model, price) values ('Saab', '9-3', '$2744.93');
insert into car (make, model, price) values ('Toyota', 'Tacoma', '$9613.58');
insert into car (make, model, price) values ('GMC', 'Envoy', '$3956.18');
insert into car (make, model, price) values ('GMC', 'Envoy', '$6887.39');
insert into car (make, model, price) values ('Dodge', 'Ram 1500', '$6416.68');
insert into car (make, model, price) values ('Mazda', 'B-Series', '$4517.74');
insert into car (make, model, price) values ('BMW', 'M3', '$1194.50');
insert into car (make, model, price) values ('BMW', '7 Series', '$3364.84');
insert into car (make, model, price) values ('Mercedes-Benz', '300TE', '$4736.14');
insert into car (make, model, price) values ('Pontiac', 'GTO', '$1476.00');
insert into car (make, model, price) values ('Cadillac', 'Fleetwood', '$6710.22');
insert into car (make, model, price) values ('Toyota', 'Avalon', '$8404.67');
insert into car (make, model, price) values ('BMW', '1 Series', '$8494.08');
insert into car (make, model, price) values ('Maserati', 'Karif', '$5215.42');
insert into car (make, model, price) values ('Lincoln', 'Mark VII', '$5451.20');
insert into car (make, model, price) values ('Hyundai', 'Tiburon', '$9863.24');
insert into car (make, model, price) values ('Volkswagen', 'GTI', '$5862.00');
insert into car (make, model, price) values ('Suzuki', 'Samurai', '$2524.17');
insert into car (make, model, price) values ('Acura', 'Integra', '$6747.48');
insert into car (make, model, price) values ('Toyota', 'Tacoma', '$2060.86');
insert into car (make, model, price) values ('BMW', '3 Series', '$5663.90');
insert into car (make, model, price) values ('Audi', '90', '$9281.11');
insert into car (make, model, price) values ('Buick', 'Century', '$7459.16');
insert into car (make, model, price) values ('Volvo', 'V50', '$8025.99');
insert into car (make, model, price) values ('Hyundai', 'XG350', '$2110.93');
insert into car (make, model, price) values ('Mercury', 'Mountaineer', '$6319.03');
insert into car (make, model, price) values ('Pontiac', 'Safari', '$9084.38');
insert into car (make, model, price) values ('Audi', 'TT', '$8640.64');
insert into car (make, model, price) values ('Ford', 'Taurus', '$2884.43');
insert into car (make, model, price) values ('Toyota', '4Runner', '$8887.60');
insert into car (make, model, price) values ('Acura', 'RL', '$4437.60');
insert into car (make, model, price) values ('Suzuki', 'Esteem', '$7639.38');
insert into car (make, model, price) values ('Saab', '9-3', '$5552.85');
insert into car (make, model, price) values ('Volkswagen', 'Passat', '$2623.56');
insert into car (make, model, price) values ('Audi', 'TT', '$6264.17');
insert into car (make, model, price) values ('Mercedes-Benz', 'M-Class', '$4553.96');
insert into car (make, model, price) values ('Lexus', 'LX', '$8641.62');
insert into car (make, model, price) values ('Volkswagen', 'Passat', '$8516.16');
insert into car (make, model, price) values ('BMW', 'M5', '$5236.84');
insert into car (make, model, price) values ('Mazda', 'B-Series', '$3883.18');
insert into car (make, model, price) values ('Nissan', 'Quest', '$2198.94');
insert into car (make, model, price) values ('Audi', 'riolet', '$6943.92');
insert into car (make, model, price) values ('Ram', '1500', '$1797.53');
insert into car (make, model, price) values ('Hyundai', 'Accent', '$9956.10');
insert into car (make, model, price) values ('Dodge', 'Challenger', '$2704.41');
insert into car (make, model, price) values ('Mitsubishi', 'Precis', '$4739.72');
insert into car (make, model, price) values ('Dodge', 'Caravan', '$1158.20');
insert into car (make, model, price) values ('Ford', 'Mustang', '$6575.17');
insert into car (make, model, price) values ('Ford', 'Explorer Sport', '$6518.90');
insert into car (make, model, price) values ('Kia', 'Sedona', '$3162.45');
insert into car (make, model, price) values ('Plymouth', 'Colt Vista', '$3025.90');
insert into car (make, model, price) values ('Scion', 'xA', '$6780.03');
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', '$9983.70');
insert into car (make, model, price) values ('Nissan', 'Maxima', '$8743.63');
insert into car (make, model, price) values ('Chevrolet', 'Tahoe', '$4134.38');
insert into car (make, model, price) values ('Lexus', 'HS', '$3004.84');
insert into car (make, model, price) values ('Plymouth', 'Acclaim', '$9248.26');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '$1651.70');
insert into car (make, model, price) values ('Toyota', 'Corolla', '$1692.77');
insert into car (make, model, price) values ('Jaguar', 'XK Series', '$1456.17');
insert into car (make, model, price) values ('Pontiac', 'Montana', '$7295.55');
insert into car (make, model, price) values ('Mazda', 'MX-6', '$3970.56');
insert into car (make, model, price) values ('Hummer', 'H3', '$3210.98');
insert into car (make, model, price) values ('Cadillac', 'DeVille', '$1426.88');
insert into car (make, model, price) values ('BMW', 'M5', '$8440.89');
insert into car (make, model, price) values ('Toyota', 'Previa', '$2365.48');
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', '$4303.50');
insert into car (make, model, price) values ('Maybach', '62', '$8505.97');
insert into car (make, model, price) values ('BMW', 'M5', '$8266.07');
insert into car (make, model, price) values ('Mercedes-Benz', 'CLS-Class', '$5332.39');
insert into car (make, model, price) values ('Buick', 'Park Avenue', '$2657.17');
insert into car (make, model, price) values ('Suzuki', 'Grand Vitara', '$4676.26');
insert into car (make, model, price) values ('Nissan', 'Armada', '$6750.87');
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', '$5338.54');
insert into car (make, model, price) values ('Mercury', 'Tracer', '$8356.02');
insert into car (make, model, price) values ('Porsche', 'Cayenne', '$2225.11');
insert into car (make, model, price) values ('Lexus', 'IS', '$7018.97');
insert into car (make, model, price) values ('Suzuki', 'Forenza', '$5624.26');
insert into car (make, model, price) values ('Saab', '900', '$5728.94');
insert into car (make, model, price) values ('Acura', 'Vigor', '$9223.47');
insert into car (make, model, price) values ('GMC', 'Savana 2500', '$3040.80');
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', '$9018.82');
insert into car (make, model, price) values ('Mitsubishi', 'Galant', '$8810.12');
insert into car (make, model, price) values ('BMW', 'Z4', '$1737.46');
insert into car (make, model, price) values ('Dodge', 'Intrepid', '$4413.46');
insert into car (make, model, price) values ('Toyota', 'Camry', '$4253.03');
insert into car (make, model, price) values ('Suzuki', 'Forenza', '$3130.27');
insert into car (make, model, price) values ('Jeep', 'Liberty', '$8149.50');
insert into car (make, model, price) values ('Acura', 'TSX', '$3853.18');
insert into car (make, model, price) values ('Volkswagen', 'Cabriolet', '$9056.43');
insert into car (make, model, price) values ('Porsche', '944', '$9063.61');
insert into car (make, model, price) values ('BMW', '7 Series', '$2604.35');
insert into car (make, model, price) values ('Mazda', 'MX-5', '$7617.69');
insert into car (make, model, price) values ('Ford', 'Explorer', '$9991.03');
insert into car (make, model, price) values ('Saab', '900', '$4337.69');
insert into car (make, model, price) values ('Pontiac', 'LeMans', '$5910.45');
insert into car (make, model, price) values ('Saab', '900', '$3177.13');
insert into car (make, model, price) values ('Porsche', '928', '$1248.39');
insert into car (make, model, price) values ('Ford', 'F150', '$7674.84');
insert into car (make, model, price) values ('Mitsubishi', 'Expo', '$9911.93');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 1500', '$2272.46');
insert into car (make, model, price) values ('Nissan', 'Leaf', '$5993.33');
insert into car (make, model, price) values ('Toyota', 'Highlander', '$9594.36');
insert into car (make, model, price) values ('Audi', 'A4', '$1760.59');
insert into car (make, model, price) values ('BMW', '6 Series', '$6243.00');
insert into car (make, model, price) values ('Chevrolet', 'Avalanche 1500', '$1944.21');
insert into car (make, model, price) values ('Jeep', 'Wrangler', '$5084.24');
insert into car (make, model, price) values ('Nissan', 'Sentra', '$9160.48');
insert into car (make, model, price) values ('Hummer', 'H1', '$7255.64');
insert into car (make, model, price) values ('Jeep', 'Cherokee', '$2890.69');
insert into car (make, model, price) values ('Chevrolet', 'S10', '$6769.19');
insert into car (make, model, price) values ('Audi', 'RS4', '$1385.54');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '$6671.30');
insert into car (make, model, price) values ('Honda', 'Civic', '$6133.33');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '$5186.69');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '$6181.77');
insert into car (make, model, price) values ('Lexus', 'IS', '$3731.22');
insert into car (make, model, price) values ('Acura', 'RDX', '$9376.85');
insert into car (make, model, price) values ('Honda', 'Accord', '$1351.69');
insert into car (make, model, price) values ('Chevrolet', 'Monte Carlo', '$5796.62');
insert into car (make, model, price) values ('Ford', 'Expedition EL', '$6128.38');
insert into car (make, model, price) values ('Mercury', 'Tracer', '$9182.63');
insert into car (make, model, price) values ('Porsche', '911', '$9214.18');
insert into car (make, model, price) values ('Infiniti', 'G', '$9652.89');
insert into car (make, model, price) values ('Mercedes-Benz', 'SLR McLaren', '$1932.48');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '$6878.03');
insert into car (make, model, price) values ('Volkswagen', 'New Beetle', '$3058.73');
insert into car (make, model, price) values ('Lincoln', 'Navigator L', '$2493.79');
insert into car (make, model, price) values ('Ford', 'Escape', '$3784.32');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', '$6881.39');
insert into car (make, model, price) values ('Honda', 'Fit', '$5982.72');
insert into car (make, model, price) values ('Kia', 'Mentor', '$1166.69');
insert into car (make, model, price) values ('Dodge', 'Ram 3500', '$6374.84');
insert into car (make, model, price) values ('Subaru', 'Leone', '$2225.62');
insert into car (make, model, price) values ('Volkswagen', 'riolet', '$9491.89');
insert into car (make, model, price) values ('Chrysler', 'Town & Country', '$4918.04');
insert into car (make, model, price) values ('Toyota', 'MR2', '$4135.41');
insert into car (make, model, price) values ('Dodge', 'Caravan', '$6199.25');
insert into car (make, model, price) values ('Subaru', 'Outback', '$7745.35');
insert into car (make, model, price) values ('Cadillac', 'STS', '$5427.91');
insert into car (make, model, price) values ('Jeep', 'Cherokee', '$3753.64');
insert into car (make, model, price) values ('Volvo', 'XC90', '$9787.86');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '$4664.01');
insert into car (make, model, price) values ('Mazda', 'B-Series', '$7439.51');
insert into car (make, model, price) values ('Chevrolet', 'Silverado', '$8813.04');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 3500', '$6477.48');
insert into car (make, model, price) values ('Volvo', 'V40', '$4996.84');
insert into car (make, model, price) values ('GMC', 'Jimmy', '$8440.67');
insert into car (make, model, price) values ('Mercedes-Benz', 'CLK-Class', '$2775.19');
insert into car (make, model, price) values ('Mazda', 'MX-3', '$7687.95');
insert into car (make, model, price) values ('Buick', 'Skyhawk', '$2337.34');
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', '$9609.64');
insert into car (make, model, price) values ('Ford', 'F350', '$2560.81');
insert into car (make, model, price) values ('Porsche', 'Cayenne', '$5184.13');
insert into car (make, model, price) values ('Maserati', 'GranTurismo', '$2291.17');
insert into car (make, model, price) values ('Chevrolet', 'TrailBlazer', '$1895.37');
insert into car (make, model, price) values ('Audi', '200', '$6598.95');
insert into car (make, model, price) values ('GMC', 'Savana 1500', '$3779.59');
insert into car (make, model, price) values ('Audi', 'V8', '$7090.15');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', '$7712.27');
insert into car (make, model, price) values ('Buick', 'LaCrosse', '$8708.20');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '$3969.02');
insert into car (make, model, price) values ('Buick', 'Regal', '$1366.22');
insert into car (make, model, price) values ('Maybach', '57', '$6671.40');
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', '$4999.87');
insert into car (make, model, price) values ('Oldsmobile', 'Achieva', '$9405.50');
insert into car (make, model, price) values ('Chevrolet', 'Avalanche 2500', '$6691.38');
insert into car (make, model, price) values ('Mercedes-Benz', '400SE', '$9889.99');
insert into car (make, model, price) values ('Ford', 'Expedition', '$1288.40');
insert into car (make, model, price) values ('Oldsmobile', '88', '$3916.05');
insert into car (make, model, price) values ('Suzuki', 'Aerio', '$7508.05');
insert into car (make, model, price) values ('Chrysler', 'Voyager', '$6288.24');
insert into car (make, model, price) values ('Volkswagen', 'Phaeton', '$3185.10');
insert into car (make, model, price) values ('Hyundai', 'Accent', '$7669.23');
insert into car (make, model, price) values ('Volvo', 'S80', '$9472.19');
insert into car (make, model, price) values ('Ford', 'E-Series', '$7217.14');
insert into car (make, model, price) values ('Nissan', 'Armada', '$6573.97');
insert into car (make, model, price) values ('Aston Martin', 'V8 Vantage S', '$4507.52');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', '$3532.32');
insert into car (make, model, price) values ('Mitsubishi', 'Montero', '$5050.70');
insert into car (make, model, price) values ('Subaru', 'Impreza', '$8809.16');
insert into car (make, model, price) values ('GMC', 'Safari', '$1965.65');
insert into car (make, model, price) values ('Cadillac', 'SRX', '$7688.72');
insert into car (make, model, price) values ('Acura', 'TL', '$5285.45');
insert into car (make, model, price) values ('Toyota', 'Sequoia', '$8771.47');
insert into car (make, model, price) values ('Nissan', '370Z', '$8356.11');
insert into car (make, model, price) values ('Kia', 'Sedona', '$4563.65');
insert into car (make, model, price) values ('Nissan', 'Frontier', '$5068.60');
insert into car (make, model, price) values ('Ford', 'Thunderbird', '$9154.37');
insert into car (make, model, price) values ('Cadillac', 'CTS-V', '$5238.72');
insert into car (make, model, price) values ('Dodge', 'D150', '$2034.45');
insert into car (make, model, price) values ('Subaru', 'Impreza WRX', '$3406.28');
insert into car (make, model, price) values ('Pontiac', 'Fiero', '$5734.32');
insert into car (make, model, price) values ('GMC', '3500 Club Coupe', '$5121.73');
insert into car (make, model, price) values ('Chevrolet', '1500', '$6441.81');
insert into car (make, model, price) values ('Hyundai', 'Azera', '$8513.96');
insert into car (make, model, price) values ('Mercury', 'Marquis', '$5975.87');
insert into car (make, model, price) values ('Chrysler', 'Crossfire', '$8762.15');
insert into car (make, model, price) values ('Mazda', 'MPV', '$8486.63');
insert into car (make, model, price) values ('Ford', 'Expedition', '$6689.32');
insert into car (make, model, price) values ('Lotus', 'Elise', '$5948.77');
insert into car (make, model, price) values ('GMC', '1500', '$3439.25');
insert into car (make, model, price) values ('Toyota', 'Land Cruiser', '$8513.67');
insert into car (make, model, price) values ('Cadillac', 'STS', '$9427.12');
insert into car (make, model, price) values ('GMC', 'Yukon', '$2132.12');
insert into car (make, model, price) values ('Plymouth', 'Colt', '$2863.04');
insert into car (make, model, price) values ('Mazda', 'Navajo', '$1640.98');
insert into car (make, model, price) values ('Toyota', 'MR2', '$4518.40');
insert into car (make, model, price) values ('Infiniti', 'J', '$6936.97');
insert into car (make, model, price) values ('Alfa Romeo', '164', '$7805.63');
insert into car (make, model, price) values ('Isuzu', 'Amigo', '$7739.05');
insert into car (make, model, price) values ('Toyota', 'Previa', '$4791.51');
insert into car (make, model, price) values ('Toyota', 'Highlander', '$9948.15');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '$4277.49');
insert into car (make, model, price) values ('Chrysler', 'Town & Country', '$6825.63');
insert into car (make, model, price) values ('Chevrolet', 'Tracker', '$3289.76');
insert into car (make, model, price) values ('BMW', 'M3', '$8903.50');
insert into car (make, model, price) values ('Jaguar', 'XK', '$2210.75');
insert into car (make, model, price) values ('Ford', 'Explorer', '$2912.03');
insert into car (make, model, price) values ('Pontiac', 'Montana SV6', '$2925.85');
insert into car (make, model, price) values ('Chevrolet', 'Sonic', '$6533.40');
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', '$8586.45');
insert into car (make, model, price) values ('Ford', 'Thunderbird', '$7739.23');
insert into car (make, model, price) values ('Ford', 'Ranger', '$2916.41');
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', '$6240.25');
insert into car (make, model, price) values ('Lexus', 'LX', '$7405.93');
insert into car (make, model, price) values ('Saturn', 'Outlook', '$9435.00');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '$6563.48');
insert into car (make, model, price) values ('Toyota', 'Camry Solara', '$9940.04');
insert into car (make, model, price) values ('Chevrolet', 'Monte Carlo', '$4596.67');
insert into car (make, model, price) values ('Honda', 'Civic', '$4378.89');
insert into car (make, model, price) values ('Honda', 'Civic', '$3559.61');
insert into car (make, model, price) values ('Audi', 'TT', '$7320.87');
insert into car (make, model, price) values ('Dodge', 'Caravan', '$9534.99');
insert into car (make, model, price) values ('Nissan', 'Pathfinder Armada', '$6330.52');
insert into car (make, model, price) values ('BMW', '5 Series', '$7068.66');
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', '$9552.87');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '$1342.36');
insert into car (make, model, price) values ('GMC', 'Sierra 1500', '$4069.30');
insert into car (make, model, price) values ('Bentley', 'Continental', '$5804.16');
insert into car (make, model, price) values ('Hyundai', 'Azera', '$1642.22');
insert into car (make, model, price) values ('Isuzu', 'Trooper', '$7425.39');
insert into car (make, model, price) values ('Subaru', 'Impreza', '$4656.61');
insert into car (make, model, price) values ('Nissan', 'Frontier', '$7899.13');
insert into car (make, model, price) values ('BMW', 'Z4', '$8764.69');
insert into car (make, model, price) values ('Ford', 'EXP', '$5402.60');
insert into car (make, model, price) values ('Pontiac', 'Montana', '$5273.85');
insert into car (make, model, price) values ('Ford', 'Econoline E350', '$3037.46');
insert into car (make, model, price) values ('Oldsmobile', 'Alero', '$1473.47');
insert into car (make, model, price) values ('Ford', 'Econoline E150', '$8184.62');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '$3118.49');
insert into car (make, model, price) values ('Mitsubishi', 'Galant', '$7113.83');
insert into car (make, model, price) values ('Cadillac', 'DeVille', '$4500.38');
insert into car (make, model, price) values ('Peugeot', '207', '$4498.79');
insert into car (make, model, price) values ('Lincoln', 'Town Car', '$1203.07');
insert into car (make, model, price) values ('Toyota', 'Celica', '$8415.76');
insert into car (make, model, price) values ('Mazda', 'RX-8', '$8393.31');
insert into car (make, model, price) values ('Cadillac', 'Fleetwood', '$8398.47');
insert into car (make, model, price) values ('Volkswagen', 'rio', '$5797.93');
insert into car (make, model, price) values ('Geo', 'Tracker', '$5281.20');
insert into car (make, model, price) values ('Chevrolet', 'Express 2500', '$5721.78');
insert into car (make, model, price) values ('Hummer', 'H3T', '$4691.62');
insert into car (make, model, price) values ('GMC', 'Savana 3500', '$9247.37');
insert into car (make, model, price) values ('Buick', 'Century', '$5898.73');
insert into car (make, model, price) values ('Subaru', 'Impreza', '$1024.38');
insert into car (make, model, price) values ('Land Rover', 'Discovery Series II', '$8498.23');
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', '$7324.71');
insert into car (make, model, price) values ('Mazda', 'Mazdaspeed6', '$1549.10');
insert into car (make, model, price) values ('Hyundai', 'Accent', '$7734.50');
insert into car (make, model, price) values ('GMC', 'Yukon', '$6633.35');
insert into car (make, model, price) values ('Mercury', 'Villager', '$8973.45');
insert into car (make, model, price) values ('Ford', 'Taurus', '$2031.60');
insert into car (make, model, price) values ('Ford', 'Bronco II', '$8005.69');
insert into car (make, model, price) values ('Ford', 'Explorer', '$4831.01');
insert into car (make, model, price) values ('Oldsmobile', 'Achieva', '$3527.45');
insert into car (make, model, price) values ('Jeep', 'Commander', '$2036.68');
insert into car (make, model, price) values ('Volkswagen', 'Eurovan', '$8830.13');
insert into car (make, model, price) values ('Oldsmobile', 'Cutlass Supreme', '$8744.52');
insert into car (make, model, price) values ('GMC', 'Sierra 3500', '$6048.17');
insert into car (make, model, price) values ('Honda', 'Accord', '$7224.48');
insert into car (make, model, price) values ('Mercedes-Benz', 'G-Class', '$4358.21');
insert into car (make, model, price) values ('Cadillac', 'Escalade EXT', '$7477.62');
insert into car (make, model, price) values ('Dodge', 'Nitro', '$1871.92');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '$6188.31');
insert into car (make, model, price) values ('GMC', 'Vandura G3500', '$9350.71');
insert into car (make, model, price) values ('Nissan', 'Pathfinder', '$2921.11');
insert into car (make, model, price) values ('Dodge', 'Viper', '$8251.48');
insert into car (make, model, price) values ('GMC', 'Savana 1500', '$7726.45');
insert into car (make, model, price) values ('Honda', 'Civic', '$4628.05');
insert into car (make, model, price) values ('Mazda', 'MX-3', '$2768.61');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', '$8891.97');
insert into car (make, model, price) values ('Kia', 'Sportage', '$6168.95');
insert into car (make, model, price) values ('Kia', 'Sportage', '$8931.92');
insert into car (make, model, price) values ('Mitsubishi', 'Galant', '$4748.88');
insert into car (make, model, price) values ('Chevrolet', 'Prizm', '$8077.77');
insert into car (make, model, price) values ('Pontiac', 'Tempest', '$6009.51');
insert into car (make, model, price) values ('Nissan', 'Frontier', '$2170.63');
insert into car (make, model, price) values ('Lincoln', 'Continental', '$1648.78');
insert into car (make, model, price) values ('Suzuki', 'SX4', '$9910.17');
insert into car (make, model, price) values ('Nissan', 'GT-R', '$8021.09');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '$8141.43');
insert into car (make, model, price) values ('Porsche', 'Carrera GT', '$1039.15');
insert into car (make, model, price) values ('Ford', 'Focus', '$9837.45');
insert into car (make, model, price) values ('Lincoln', 'Continental', '$1712.71');
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', '$2061.06');
insert into car (make, model, price) values ('Maserati', '228', '$7948.57');
insert into car (make, model, price) values ('Volkswagen', 'Touareg', '$7517.84');
insert into car (make, model, price) values ('Honda', 'Pilot', '$5834.42');
insert into car (make, model, price) values ('GMC', 'Yukon XL 1500', '$6295.72');
insert into car (make, model, price) values ('Toyota', 'Tacoma', '$1104.93');
insert into car (make, model, price) values ('Chevrolet', 'S10', '$9014.69');
insert into car (make, model, price) values ('Ford', 'E350', '$3478.88');
insert into car (make, model, price) values ('Hummer', 'H2 SUV', '$5125.30');
insert into car (make, model, price) values ('Oldsmobile', 'Aurora', '$6121.67');
insert into car (make, model, price) values ('Mitsubishi', 'Truck', '$2300.27');
insert into car (make, model, price) values ('Mitsubishi', 'Mirage', '$3519.95');
insert into car (make, model, price) values ('Lincoln', 'LS', '$8971.60');
insert into car (make, model, price) values ('Ram', '2500', '$1552.16');
insert into car (make, model, price) values ('Chevrolet', 'HHR', '$4803.13');
insert into car (make, model, price) values ('Saab', '9000', '$2504.18');
insert into car (make, model, price) values ('Chrysler', '300M', '$7684.48');
insert into car (make, model, price) values ('Nissan', 'Xterra', '$9380.93');
insert into car (make, model, price) values ('Subaru', 'Loyale', '$8856.26');
insert into car (make, model, price) values ('GMC', 'Sierra', '$5569.99');
insert into car (make, model, price) values ('Dodge', 'Ram 2500', '$3555.62');
insert into car (make, model, price) values ('Acura', 'MDX', '$2938.96');
insert into car (make, model, price) values ('Volkswagen', 'GTI', '$9245.09');
insert into car (make, model, price) values ('Honda', 'Civic', '$2424.82');
insert into car (make, model, price) values ('Suzuki', 'Grand Vitara', '$2927.84');
insert into car (make, model, price) values ('Infiniti', 'QX56', '$1855.99');
insert into car (make, model, price) values ('Mazda', 'Navajo', '$3595.16');
insert into car (make, model, price) values ('Lexus', 'ES', '$2747.21');
insert into car (make, model, price) values ('Ford', 'Aerostar', '$2310.56');
insert into car (make, model, price) values ('Ford', 'E-Series', '$6071.57');
insert into car (make, model, price) values ('Toyota', 'MR2', '$1635.59');
insert into car (make, model, price) values ('Mercury', 'Mountaineer', '$6131.56');
insert into car (make, model, price) values ('Mazda', 'B-Series', '$7353.19');
insert into car (make, model, price) values ('Subaru', 'Outback', '$3915.12');
insert into car (make, model, price) values ('BMW', 'X5', '$3577.37');
insert into car (make, model, price) values ('Honda', 'Civic', '$2852.20');
insert into car (make, model, price) values ('Chevrolet', 'Blazer', '$6165.91');
insert into car (make, model, price) values ('Mitsubishi', 'RVR', '$1717.76');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '$2122.17');
insert into car (make, model, price) values ('Honda', 'Pilot', '$6571.84');
insert into car (make, model, price) values ('Toyota', 'Venza', '$7946.90');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 3500', '$6082.38');
insert into car (make, model, price) values ('Ford', 'Ranger', '$9990.77');
insert into car (make, model, price) values ('Pontiac', 'Sunfire', '$5040.80');
insert into car (make, model, price) values ('Mazda', 'MX-5', '$2217.53');
insert into car (make, model, price) values ('GMC', 'Acadia', '$8389.80');
insert into car (make, model, price) values ('Chevrolet', 'HHR', '$3106.74');
insert into car (make, model, price) values ('Ford', 'Explorer', '$1338.33');
insert into car (make, model, price) values ('Kia', 'Sportage', '$4478.36');
insert into car (make, model, price) values ('Mercedes-Benz', '500SEL', '$4686.33');
insert into car (make, model, price) values ('Buick', 'Regal', '$3917.34');
insert into car (make, model, price) values ('Mercedes-Benz', '400SEL', '$7317.34');
insert into car (make, model, price) values ('Toyota', '4Runner', '$2846.82');
insert into car (make, model, price) values ('Infiniti', 'QX', '$5942.11');
insert into car (make, model, price) values ('Infiniti', 'Q', '$5509.88');
insert into car (make, model, price) values ('Jeep', 'Patriot', '$1641.56');
insert into car (make, model, price) values ('Ferrari', '430 Scuderia', '$3356.52');
insert into car (make, model, price) values ('Lotus', 'Exige', '$5885.04');
insert into car (make, model, price) values ('Land Rover', 'Defender Ice Edition', '$5439.03');
insert into car (make, model, price) values ('Subaru', 'Impreza', '$7399.61');
insert into car (make, model, price) values ('Toyota', 'Tacoma', '$3746.33');
insert into car (make, model, price) values ('Dodge', 'Ram', '$3005.79');
insert into car (make, model, price) values ('Mercury', 'Cougar', '$5867.11');
insert into car (make, model, price) values ('Buick', 'Rendezvous', '$1852.42');
insert into car (make, model, price) values ('Audi', '100', '$9822.47');
insert into car (make, model, price) values ('Land Rover', 'Freelander', '$8281.17');
insert into car (make, model, price) values ('Cadillac', 'CTS-V', '$2064.81');
insert into car (make, model, price) values ('Ford', 'Aspire', '$1799.98');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '$2959.11');
insert into car (make, model, price) values ('Mazda', 'Mazda3', '$9290.35');
insert into car (make, model, price) values ('Saab', '9-2X', '$3178.74');
insert into car (make, model, price) values ('Ford', 'Tempo', '$6648.27');
insert into car (make, model, price) values ('Volvo', '850', '$3782.11');
insert into car (make, model, price) values ('Isuzu', 'Oasis', '$6825.81');
insert into car (make, model, price) values ('BMW', 'X5', '$5112.11');
insert into car (make, model, price) values ('Ford', 'F-Series', '$1352.49');
insert into car (make, model, price) values ('Mazda', 'CX-9', '$4327.21');
insert into car (make, model, price) values ('Acura', 'RDX', '$2047.53');
insert into car (make, model, price) values ('Nissan', '370Z', '$2129.73');
insert into car (make, model, price) values ('Bentley', 'Continental', '$3382.23');
insert into car (make, model, price) values ('Ford', 'Crown Victoria', '$1889.69');
insert into car (make, model, price) values ('Lincoln', 'Town Car', '$1508.21');
insert into car (make, model, price) values ('Hyundai', 'Santa Fe', '$4941.67');
insert into car (make, model, price) values ('Lotus', 'Exige', '$4333.34');
insert into car (make, model, price) values ('Nissan', 'Titan', '$4786.13');
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', '$8245.12');
insert into car (make, model, price) values ('Chevrolet', 'Express 1500', '$2564.35');
insert into car (make, model, price) values ('Mitsubishi', 'Pajero', '$2887.65');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 1500', '$4491.70');
insert into car (make, model, price) values ('Maybach', '62', '$3424.74');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '$7846.01');
insert into car (make, model, price) values ('Dodge', 'Viper', '$3256.77');
insert into car (make, model, price) values ('Saab', '9-5', '$6977.57');
insert into car (make, model, price) values ('GMC', 'Savana 1500', '$5693.87');
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', '$5754.11');
insert into car (make, model, price) values ('Jeep', 'Wrangler', '$1156.90');
insert into car (make, model, price) values ('Volkswagen', 'GTI', '$7732.49');
insert into car (make, model, price) values ('Mazda', 'Protege', '$4983.06');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '$4208.65');
insert into car (make, model, price) values ('Lexus', 'ES', '$2413.71');
insert into car (make, model, price) values ('Jaguar', 'XJ Series', '$4499.82');
insert into car (make, model, price) values ('Honda', 'Odyssey', '$7600.71');
insert into car (make, model, price) values ('Eagle', 'Vision', '$5755.02');
insert into car (make, model, price) values ('Ford', 'F150', '$3415.12');
insert into car (make, model, price) values ('Nissan', '240SX', '$7935.08');
insert into car (make, model, price) values ('Buick', 'LeSabre', '$1144.66');
insert into car (make, model, price) values ('GMC', '1500', '$4486.32');
insert into car (make, model, price) values ('Suzuki', 'Sidekick', '$5151.60');
insert into car (make, model, price) values ('Nissan', 'Sentra', '$2942.64');
insert into car (make, model, price) values ('Porsche', '911', '$7966.05');
insert into car (make, model, price) values ('Chevrolet', '2500', '$6499.32');
insert into car (make, model, price) values ('Chevrolet', 'S10', '$7065.94');
insert into car (make, model, price) values ('Ford', 'Crown Victoria', '$7970.35');
insert into car (make, model, price) values ('GMC', 'Jimmy', '$9775.74');
insert into car (make, model, price) values ('Dodge', 'Durango', '$4086.03');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '$4160.64');
insert into car (make, model, price) values ('MINI', 'Cooper', '$7929.16');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '$7096.67');
insert into car (make, model, price) values ('Subaru', 'Legacy', '$2220.05');
insert into car (make, model, price) values ('Ford', 'Explorer Sport Trac', '$3365.73');
insert into car (make, model, price) values ('Porsche', 'Cayman', '$5071.32');
insert into car (make, model, price) values ('Nissan', 'Frontier', '$6148.09');
insert into car (make, model, price) values ('GMC', '2500', '$4379.37');
insert into car (make, model, price) values ('Volkswagen', 'Eurovan', '$1692.37');
insert into car (make, model, price) values ('Audi', 'R8', '$3814.53');
insert into car (make, model, price) values ('Lexus', 'HS', '$1696.61');
insert into car (make, model, price) values ('Nissan', 'Maxima', '$7275.78');
insert into car (make, model, price) values ('Ford', 'Aerostar', '$3497.08');
insert into car (make, model, price) values ('Mitsubishi', 'Pajero', '$4263.74');
insert into car (make, model, price) values ('Holden', 'VS Commodore', '$5614.72');
insert into car (make, model, price) values ('Suzuki', 'SX4', '$3116.92');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '$1744.83');
insert into car (make, model, price) values ('GMC', 'Savana 2500', '$2496.82');
insert into car (make, model, price) values ('Mercury', 'Sable', '$2295.56');
insert into car (make, model, price) values ('Volvo', 'S60', '$4848.67');
insert into car (make, model, price) values ('Hyundai', 'Equus', '$1099.69');
insert into car (make, model, price) values ('Suzuki', 'Swift', '$6880.51');
insert into car (make, model, price) values ('Volkswagen', 'Eurovan', '$4941.01');
insert into car (make, model, price) values ('Chrysler', 'LHS', '$6217.95');
insert into car (make, model, price) values ('Mercury', 'Lynx', '$1722.68');
insert into car (make, model, price) values ('Lotus', 'Exige', '$6624.84');
insert into car (make, model, price) values ('Oldsmobile', 'Cutlass', '$4164.44');
insert into car (make, model, price) values ('Acura', 'Legend', '$6007.28');
insert into car (make, model, price) values ('Ford', 'E-Series', '$7468.87');
insert into car (make, model, price) values ('Lotus', 'Exige', '$9750.61');
insert into car (make, model, price) values ('BMW', '760', '$7355.85');
insert into car (make, model, price) values ('Lincoln', 'Navigator', '$3334.02');
insert into car (make, model, price) values ('GMC', 'Yukon XL 2500', '$5816.69');
insert into car (make, model, price) values ('Lexus', 'RX', '$8482.45');
insert into car (make, model, price) values ('Mitsubishi', 'Montero', '$6310.28');
insert into car (make, model, price) values ('Jaguar', 'XJ Series', '$2010.29');
insert into car (make, model, price) values ('Toyota', 'Tundra', '$8811.64');
insert into car (make, model, price) values ('Pontiac', '1000', '$4951.47');
insert into car (make, model, price) values ('Honda', 'Insight', '$6091.98');
insert into car (make, model, price) values ('Mercedes-Benz', 'W201', '$2159.85');
insert into car (make, model, price) values ('Lincoln', 'Continental', '$5729.71');
insert into car (make, model, price) values ('Saab', '9-3', '$7889.73');
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', '$5663.79');
insert into car (make, model, price) values ('Porsche', 'Panamera', '$7161.99');
insert into car (make, model, price) values ('Ford', 'E250', '$7124.37');
insert into car (make, model, price) values ('Chevrolet', 'Classic', '$4504.85');
insert into car (make, model, price) values ('Mitsubishi', 'Galant', '$7053.21');
insert into car (make, model, price) values ('Mercury', 'Villager', '$8434.14');
insert into car (make, model, price) values ('Kia', 'Spectra', '$6831.53');
insert into car (make, model, price) values ('Chevrolet', 'Blazer', '$6626.00');
insert into car (make, model, price) values ('Dodge', 'Ram', '$3641.64');
insert into car (make, model, price) values ('Dodge', 'Colt', '$5698.68');
insert into car (make, model, price) values ('Volvo', 'S80', '$9395.61');
insert into car (make, model, price) values ('Volvo', 'C70', '$7845.38');
insert into car (make, model, price) values ('Subaru', 'BRZ', '$2399.41');
insert into car (make, model, price) values ('Hummer', 'H3T', '$6145.22');
insert into car (make, model, price) values ('Audi', 'Q5', '$2096.00');
insert into car (make, model, price) values ('Maybach', '57', '$3101.83');
insert into car (make, model, price) values ('Volkswagen', 'Touareg', '$4198.18');
insert into car (make, model, price) values ('Infiniti', 'FX', '$4604.89');
insert into car (make, model, price) values ('Suzuki', 'Swift', '$9655.43');
insert into car (make, model, price) values ('Toyota', 'Celica', '$9624.16');
insert into car (make, model, price) values ('Lexus', 'RX Hybrid', '$4498.51');
insert into car (make, model, price) values ('Acura', 'RL', '$8245.87');
insert into car (make, model, price) values ('Infiniti', 'QX', '$1842.75');
insert into car (make, model, price) values ('Saab', '900', '$1477.22');
insert into car (make, model, price) values ('Saab', '900', '$5196.07');
insert into car (make, model, price) values ('Mazda', '929', '$8549.08');
insert into car (make, model, price) values ('Infiniti', 'J', '$8811.71');
insert into car (make, model, price) values ('Pontiac', 'Monterey', '$7273.25');
insert into car (make, model, price) values ('Mitsubishi', 'Truck', '$4196.64');
insert into car (make, model, price) values ('Suzuki', 'Swift', '$6759.02');
insert into car (make, model, price) values ('Hyundai', 'Sonata', '$7892.61');
insert into car (make, model, price) values ('Ford', 'Explorer', '$6193.97');
insert into car (make, model, price) values ('Dodge', 'Dakota Club', '$9678.22');
insert into car (make, model, price) values ('Subaru', 'Leone', '$4689.66');
insert into car (make, model, price) values ('BMW', '3 Series', '$1674.25');
insert into car (make, model, price) values ('Austin', 'Mini Cooper', '$7277.65');
insert into car (make, model, price) values ('Mitsubishi', 'L300', '$6719.10');
insert into car (make, model, price) values ('Volvo', 'S60', '$2930.86');
insert into car (make, model, price) values ('Kia', 'Borrego', '$9199.63');
insert into car (make, model, price) values ('Mercedes-Benz', '500E', '$6678.83');
insert into car (make, model, price) values ('Volvo', 'V70', '$1360.15');
insert into car (make, model, price) values ('Chrysler', '300M', '$9525.90');
insert into car (make, model, price) values ('Dodge', 'Spirit', '$8377.71');
insert into car (make, model, price) values ('Mazda', 'Millenia', '$1165.95');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '$2777.13');
insert into car (make, model, price) values ('Isuzu', 'Trooper', '$9776.60');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', '$6181.15');
insert into car (make, model, price) values ('Ford', 'F150', '$7701.18');
insert into car (make, model, price) values ('Volvo', 'S80', '$6190.43');
insert into car (make, model, price) values ('Ford', 'Probe', '$9434.87');
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', '$6562.40');
insert into car (make, model, price) values ('Ford', 'GT500', '$2356.40');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', '$1359.14');
insert into car (make, model, price) values ('Pontiac', 'Grand Am', '$2520.08');
insert into car (make, model, price) values ('Mitsubishi', 'Montero', '$3244.85');
insert into car (make, model, price) values ('Mazda', 'Mazdaspeed6', '$9390.05');
insert into car (make, model, price) values ('Buick', 'Reatta', '$1282.42');
insert into car (make, model, price) values ('Mazda', 'Protege', '$9242.87');
insert into car (make, model, price) values ('GMC', 'Savana 3500', '$8454.81');
insert into car (make, model, price) values ('Suzuki', 'Swift', '$1482.17');
insert into car (make, model, price) values ('Acura', 'RDX', '$1150.09');
insert into car (make, model, price) values ('Toyota', 'Sienna', '$6848.85');
insert into car (make, model, price) values ('Mazda', 'MX-6', '$4323.78');
insert into car (make, model, price) values ('Bentley', 'Continental Super', '$8972.48');
insert into car (make, model, price) values ('Audi', 'Q5', '$7264.87');
insert into car (make, model, price) values ('BMW', 'M6', '$9608.63');
insert into car (make, model, price) values ('Audi', 'A5', '$6245.23');
insert into car (make, model, price) values ('Volkswagen', 'Beetle', '$3679.52');
insert into car (make, model, price) values ('Mercury', 'Sable', '$2855.65');
insert into car (make, model, price) values ('Toyota', '4Runner', '$9833.78');
insert into car (make, model, price) values ('Maserati', 'GranTurismo', '$4125.80');
insert into car (make, model, price) values ('Volvo', 'C70', '$5055.88');
insert into car (make, model, price) values ('Chevrolet', 'Camaro', '$2937.19');
insert into car (make, model, price) values ('Hyundai', 'Tiburon', '$9146.82');
insert into car (make, model, price) values ('Cadillac', 'Seville', '$7850.82');
insert into car (make, model, price) values ('Ford', 'Explorer', '$6655.98');
insert into car (make, model, price) values ('Dodge', 'Dakota', '$1308.78');
insert into car (make, model, price) values ('Volkswagen', 'New Beetle', '$1967.17');
insert into car (make, model, price) values ('Ford', 'F-Series Super Duty', '$5921.34');
insert into car (make, model, price) values ('Toyota', 'RAV4', '$9984.50');
insert into car (make, model, price) values ('BMW', '1 Series', '$5024.15');
insert into car (make, model, price) values ('Volvo', 'V50', '$2871.78');
insert into car (make, model, price) values ('Mercedes-Benz', 'M-Class', '$6638.01');
insert into car (make, model, price) values ('Kia', 'Sportage', '$9691.66');
insert into car (make, model, price) values ('Ford', 'E150', '$8923.56');
insert into car (make, model, price) values ('Toyota', 'Tercel', '$4898.42');
insert into car (make, model, price) values ('Toyota', 'Celica', '$3888.98');
insert into car (make, model, price) values ('Dodge', 'Intrepid', '$5264.61');
insert into car (make, model, price) values ('Lotus', 'Esprit', '$9714.16');
insert into car (make, model, price) values ('Mitsubishi', 'Expo', '$8236.04');
insert into car (make, model, price) values ('Ford', 'F-Series Super Duty', '$7133.01');
insert into car (make, model, price) values ('GMC', 'Yukon Denali', '$2789.13');
insert into car (make, model, price) values ('Chevrolet', 'Astro', '$5214.10');
insert into car (make, model, price) values ('Lincoln', 'Town Car', '$2546.49');
insert into car (make, model, price) values ('Infiniti', 'QX', '$9866.87');
insert into car (make, model, price) values ('Pontiac', 'Daewoo Kalos', '$4835.57');
insert into car (make, model, price) values ('Volvo', 'V70', '$4273.57');
insert into car (make, model, price) values ('Kia', 'Optima', '$6517.36');
insert into car (make, model, price) values ('Land Rover', 'Defender 110', '$7573.81');
insert into car (make, model, price) values ('GMC', '2500 Club Coupe', '$4815.11');
insert into car (make, model, price) values ('Suzuki', 'Esteem', '$8102.21');
insert into car (make, model, price) values ('Jeep', 'Liberty', '$7148.63');
insert into car (make, model, price) values ('Kia', 'Spectra', '$6510.94');
insert into car (make, model, price) values ('Infiniti', 'M', '$6168.55');
insert into car (make, model, price) values ('Chevrolet', 'Equinox', '$7342.52');
insert into car (make, model, price) values ('Nissan', 'Pathfinder', '$2686.94');
insert into car (make, model, price) values ('Isuzu', 'i-280', '$6341.21');
insert into car (make, model, price) values ('Toyota', 'Tacoma', '$3507.51');
insert into car (make, model, price) values ('Volkswagen', 'GTI', '$8562.14');
insert into car (make, model, price) values ('Lincoln', 'Town Car', '$9923.04');
insert into car (make, model, price) values ('Volvo', '850', '$5002.53');
insert into car (make, model, price) values ('Scion', 'xD', '$3595.70');
insert into car (make, model, price) values ('Mazda', 'MX-5', '$3834.75');
insert into car (make, model, price) values ('Acura', 'NSX', '$8219.18');
insert into car (make, model, price) values ('Mitsubishi', 'Lancer Evolution', '$7123.08');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '$1884.71');
insert into car (make, model, price) values ('Jeep', 'Commander', '$5461.04');
insert into car (make, model, price) values ('Toyota', 'Celica', '$5942.23');
insert into car (make, model, price) values ('Porsche', '914', '$6233.00');
insert into car (make, model, price) values ('Lamborghini', 'Diablo', '$3836.57');
insert into car (make, model, price) values ('Cadillac', 'SRX', '$9157.46');
insert into car (make, model, price) values ('Ford', 'Ranger', '$9986.08');
insert into car (make, model, price) values ('Toyota', 'Corolla', '$2984.28');
insert into car (make, model, price) values ('Chevrolet', 'G-Series G20', '$1368.24');
insert into car (make, model, price) values ('Chevrolet', 'Sportvan G30', '$8293.82');
insert into car (make, model, price) values ('Aptera', 'Typ-1', '$7137.71');
insert into car (make, model, price) values ('Chevrolet', 'Classic', '$6971.62');
insert into car (make, model, price) values ('Chrysler', 'Sebring', '$6104.43');
insert into car (make, model, price) values ('Isuzu', 'Ascender', '$1099.01');
insert into car (make, model, price) values ('BMW', '530', '$7122.53');
insert into car (make, model, price) values ('Nissan', 'Maxima', '$6751.04');
insert into car (make, model, price) values ('Mitsubishi', 'Mirage', '$2319.66');
insert into car (make, model, price) values ('Chrysler', 'LHS', '$1386.60');
insert into car (make, model, price) values ('Lincoln', 'Navigator', '$8802.38');
insert into car (make, model, price) values ('Buick', 'Century', '$1270.47');
insert into car (make, model, price) values ('Chevrolet', 'Aveo', '$5077.37');
insert into car (make, model, price) values ('Ford', 'F-Series', '$3711.13');
insert into car (make, model, price) values ('Cadillac', 'Fleetwood', '$7633.24');
insert into car (make, model, price) values ('Chevrolet', '2500', '$8570.88');
insert into car (make, model, price) values ('Maybach', '62', '$8821.95');
insert into car (make, model, price) values ('Mazda', 'Protege', '$7531.95');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '$5990.42');
insert into car (make, model, price) values ('Mercedes-Benz', 'Sprinter 3500', '$1957.19');
insert into car (make, model, price) values ('Mazda', 'B-Series', '$2013.92');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '$3327.20');
insert into car (make, model, price) values ('Saab', '9-3', '$7706.81');
insert into car (make, model, price) values ('Hyundai', 'Tiburon', '$8908.08');
insert into car (make, model, price) values ('Ford', 'F350', '$9240.99');
insert into car (make, model, price) values ('Honda', 'Civic Si', '$2055.00');
insert into car (make, model, price) values ('Nissan', 'Sentra', '$4989.53');
insert into car (make, model, price) values ('GMC', 'Sierra 1500', '$5912.48');
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', '$9261.98');
insert into car (make, model, price) values ('Land Rover', 'Freelander', '$3621.12');
insert into car (make, model, price) values ('Honda', 'Pilot', '$2094.30');
insert into car (make, model, price) values ('Chevrolet', 'Express 3500', '$8655.89');
insert into car (make, model, price) values ('BMW', '325', '$2084.88');
insert into car (make, model, price) values ('Volkswagen', 'GTI', '$5879.13');
insert into car (make, model, price) values ('Ford', 'Explorer Sport Trac', '$4266.64');
insert into car (make, model, price) values ('Toyota', 'T100', '$9484.71');
insert into car (make, model, price) values ('BMW', '325', '$9617.68');
insert into car (make, model, price) values ('Suzuki', 'Grand Vitara', '$6306.28');
insert into car (make, model, price) values ('Ford', 'F250', '$2109.09');
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', '$4016.63');
insert into car (make, model, price) values ('Chevrolet', '2500', '$9163.40');
insert into car (make, model, price) values ('Ford', 'Ranger', '$5149.75');
insert into car (make, model, price) values ('Volvo', '960', '$4265.77');
insert into car (make, model, price) values ('Kia', 'Sorento', '$2481.44');
insert into car (make, model, price) values ('Oldsmobile', 'Cutlass Supreme', '$9954.56');
insert into car (make, model, price) values ('Jaguar', 'XK Series', '$5644.11');
insert into car (make, model, price) values ('Volkswagen', 'New Beetle', '$3616.20');
insert into car (make, model, price) values ('Mitsubishi', 'Montero Sport', '$5720.26');
insert into car (make, model, price) values ('Mitsubishi', 'Galant', '$7003.88');
insert into car (make, model, price) values ('Cadillac', 'DeVille', '$9341.07');
insert into car (make, model, price) values ('Scion', 'xB', '$4882.33');
insert into car (make, model, price) values ('MINI', 'Clubman', '$7392.53');
insert into car (make, model, price) values ('Dodge', 'Dakota', '$8922.39');
insert into car (make, model, price) values ('Infiniti', 'Q', '$1257.13');
insert into car (make, model, price) values ('Ford', 'Mustang', '$4506.07');
insert into car (make, model, price) values ('Maybach', '57', '$2848.62');
insert into car (make, model, price) values ('Jaguar', 'S-Type', '$4335.02');
insert into car (make, model, price) values ('Toyota', 'Tacoma Xtra', '$5180.90');
insert into car (make, model, price) values ('Cadillac', 'XLR-V', '$7463.34');
insert into car (make, model, price) values ('Dodge', 'Ram Van 1500', '$8044.39');
insert into car (make, model, price) values ('Acura', 'Integra', '$8547.79');
insert into car (make, model, price) values ('Honda', 'Ridgeline', '$7146.11');
insert into car (make, model, price) values ('Toyota', 'Sienna', '$3870.45');
insert into car (make, model, price) values ('Honda', 'Odyssey', '$7280.26');
insert into car (make, model, price) values ('Cadillac', 'DTS', '$7844.89');
insert into car (make, model, price) values ('BMW', 'X5', '$3150.23');
insert into car (make, model, price) values ('Mazda', 'B2600', '$2867.42');
insert into car (make, model, price) values ('Ford', 'Club Wagon', '$8333.54');
insert into car (make, model, price) values ('Plymouth', 'Grand Voyager', '$9041.41');
insert into car (make, model, price) values ('Mitsubishi', 'Chariot', '$4877.21');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '$8975.08');
insert into car (make, model, price) values ('MINI', 'Cooper', '$7402.53');
insert into car (make, model, price) values ('Mercury', 'Cougar', '$1472.90');
insert into car (make, model, price) values ('Chevrolet', 'Avalanche 1500', '$6618.40');
insert into car (make, model, price) values ('Lincoln', 'Mark VIII', '$7830.01');
insert into car (make, model, price) values ('Honda', 'Civic GX', '$1715.77');
insert into car (make, model, price) values ('Infiniti', 'G', '$8785.09');
insert into car (make, model, price) values ('Lotus', 'Esprit', '$4309.80');
insert into car (make, model, price) values ('Hyundai', 'Accent', '$9716.70');
insert into car (make, model, price) values ('Suzuki', 'Grand Vitara', '$1829.46');
insert into car (make, model, price) values ('GMC', '2500 Club Coupe', '$8474.23');
insert into car (make, model, price) values ('Corbin', 'Sparrow', '$5506.76');
insert into car (make, model, price) values ('Nissan', 'Sentra', '$8985.73');
insert into car (make, model, price) values ('Lotus', 'Exige', '$3040.57');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '$6810.79');
insert into car (make, model, price) values ('Buick', 'Park Avenue', '$5490.64');
insert into car (make, model, price) values ('BMW', '600', '$8864.12');
insert into car (make, model, price) values ('Honda', 'S2000', '$5725.08');
insert into car (make, model, price) values ('Subaru', 'Brat', '$5906.58');
insert into car (make, model, price) values ('BMW', '7 Series', '$7180.36');
insert into car (make, model, price) values ('Hyundai', 'Elantra', '$2536.51');
insert into car (make, model, price) values ('Mazda', 'RX-7', '$8305.83');
insert into car (make, model, price) values ('Alfa Romeo', '164', '$5414.76');
insert into car (make, model, price) values ('Mercedes-Benz', 'Sprinter 2500', '$6671.93');
insert into car (make, model, price) values ('Honda', 'Odyssey', '$7501.85');
insert into car (make, model, price) values ('Mitsubishi', 'Lancer', '$6251.14');
insert into car (make, model, price) values ('Dodge', 'Ram', '$8454.32');
insert into car (make, model, price) values ('Ford', 'Transit Connect', '$2177.46');
insert into car (make, model, price) values ('Lincoln', 'Mark VIII', '$3526.70');
insert into car (make, model, price) values ('Mitsubishi', 'Precis', '$2024.50');
insert into car (make, model, price) values ('Chrysler', 'Town & Country', '$2732.40');
insert into car (make, model, price) values ('GMC', 'Savana 1500', '$4909.49');
insert into car (make, model, price) values ('Ford', 'Fairlane', '$9148.92');
insert into car (make, model, price) values ('Eagle', 'Summit', '$8971.37');
insert into car (make, model, price) values ('Jeep', 'Cherokee', '$6012.08');
insert into car (make, model, price) values ('Tesla', 'Model S', '$3134.95');
insert into car (make, model, price) values ('Pontiac', 'Firefly', '$3291.29');
insert into car (make, model, price) values ('Volkswagen', 'Cabriolet', '$7912.00');
insert into car (make, model, price) values ('GMC', 'Safari', '$8702.85');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', '$7212.25');
insert into car (make, model, price) values ('Honda', 'Ridgeline', '$6762.37');
insert into car (make, model, price) values ('Chrysler', 'New Yorker', '$1817.71');
insert into car (make, model, price) values ('Lincoln', 'Navigator L', '$3624.75');
insert into car (make, model, price) values ('Mitsubishi', 'Pajero', '$2551.91');
insert into car (make, model, price) values ('Land Rover', 'Range Rover Sport', '$6333.57');
insert into car (make, model, price) values ('Subaru', 'XT', '$3395.47');
insert into car (make, model, price) values ('Chevrolet', 'Impala', '$3803.65');
insert into car (make, model, price) values ('Audi', 'A6', '$2208.12');
insert into car (make, model, price) values ('Chevrolet', 'Express 3500', '$4702.19');
insert into car (make, model, price) values ('Volvo', '850', '$4755.50');
insert into car (make, model, price) values ('Chevrolet', 'Malibu', '$1796.80');
insert into car (make, model, price) values ('Nissan', '300ZX', '$1337.68');
insert into car (make, model, price) values ('Mercedes-Benz', 'CLK-Class', '$6769.72');
insert into car (make, model, price) values ('Ford', 'Tempo', '$8477.15');
insert into car (make, model, price) values ('Aston Martin', 'V8 Vantage', '$3497.42');
insert into car (make, model, price) values ('Infiniti', 'M', '$5741.28');
insert into car (make, model, price) values ('Subaru', 'Legacy', '$1593.10');
insert into car (make, model, price) values ('Audi', 'S4', '$4603.87');
insert into car (make, model, price) values ('Mazda', 'RX-7', '$4525.53');
insert into car (make, model, price) values ('Audi', 'S5', '$5705.24');
insert into car (make, model, price) values ('Pontiac', 'Bonneville', '$7592.05');
insert into car (make, model, price) values ('Lexus', 'LS', '$5633.96');
insert into car (make, model, price) values ('Dodge', 'Caliber', '$7998.70');
insert into car (make, model, price) values ('Ford', 'Explorer', '$7407.94');
insert into car (make, model, price) values ('Ford', 'Tempo', '$7118.19');
insert into car (make, model, price) values ('Lexus', 'LS', '$4242.73');
insert into car (make, model, price) values ('Chevrolet', 'Tracker', '$8752.55');
insert into car (make, model, price) values ('BMW', '525', '$7628.42');
insert into car (make, model, price) values ('Infiniti', 'M', '$9816.30');
insert into car (make, model, price) values ('Dodge', 'Dakota Club', '$1308.54');
insert into car (make, model, price) values ('Chevrolet', 'Equinox', '$3407.66');
insert into car (make, model, price) values ('Lexus', 'LS', '$9444.75');
insert into car (make, model, price) values ('Jeep', 'Wrangler', '$5723.83');
