-- how to insert records into table 
INSERT INTO person (
    first_name,
    last_name,
    gender,
    date_of_birth
)
VALUES ('Anne', 'Smith', 'FEMALE', DATE `1988-01-09`);


INSERT INTO person(first_name, last_name, gender, date_of_birth, email)
VALUES ('Jake', 'Jones', 'MALE', DATE '1990-12-10', 'jake@gmail.com');

INSERT INTO person(first_name, last_name, gender, date_of_birth)
VALUES ('Anne', 'Smith', 'FEMALE', DATE '1988-01-09');

SELECT * FROM person;